FROM nginx

# File Author / Maintainer
MAINTAINER Malik Lakhani

# Copy custom configuration file from the current directory
COPY ./nginx.conf /etc/nginx/nginx.conf
# CMD ["nginx"]

# Expose ports.
EXPOSE 80